### ISSUE TITLE
Add Problem and solution section in Readme.md

### ISSUE THREAD

**Issue by shreyad2806** [tanishaness/SPROCTOR#19]
This will show proper information for your contributors and will help them understand.
![image](https://github.com/user-attachments/assets/57a3be77-d8af-42f5-b147-894a2797fb0c)

**Comment by tanishaness** [comment]
Kindly make sure you add the problem and solution related to the project only, also fix the two images not being showed in the readme.md file.

**Comment by shreyad2806** [comment]
ok
