### ISSUE TITLE
feat : Change the graph for a better visualization

### ISSUE THREAD

**Issue by Ananya-vastare** [tanishaness/SPROCTOR#22]
Instead of using a bar graph for we can use a heatmap . By using a heatmap, we not only make our data more accessible but also allow for a deeper understanding of its underlying patterns and changes.
I am a gssoc contributor please assing this issue to me with the level and hackoberfest

**Comment by Ananya-vastare** [comment]
Can you please mention the level @tanishaness

**Comment by tanishaness** [comment]
please connect the graph with a database, it will help you jump to level 3, as the graph activity is tracked but not saved in order to generate the report which is the end product of this project!

**Comment by Ananya-vastare** [comment]
What about the level?!?
