### ISSUE TITLE
Organised Read Me File

### ISSUE THREAD

**Issue by Muskan-bhatt249** [tanishaness/SPROCTOR#3]
All details regarding the project and all the necessary instructions for the contributors to follow would be added in an organised manner in the read me file.

**Comment by Muskan-bhatt249** [comment]
@tanishaness Please also add Gssoc-ext 24 and hactoberfest-accepted and level label

**Comment by Muskan-bhatt249** [comment]
@tanishaness You have not added the labels yet and hence my contribution did not give me points according to the guidelines, I once again request you to add the labels so I can earn credits for it Please.

**Comment by tanishaness** [comment]
> @tanishaness You have not added the labels yet and hence my contribution did not give me points according to the guidelines, I once again request you to add the labels so I can earn credits for it Please.

Check it now, sorry for the delay

**Comment by Muskan-bhatt249** [comment]
@tanishaness Thank you so much, can you please also add the label hactoberfest-accepted
