### ISSUE TITLE
Want to improve the look

### ISSUE THREAD

**Issue by Dipanita45** [tanishaness/SPROCTOR#37]
Add or update features of the website to make attractive

**Comment by tanishaness** [comment]
we would have to make a website/ webapp from scratch, either in react or node

**Comment by tanishaness** [comment]
@Varsha567 @theomkardeshpande @smog-root @Dipanita45 @Ananya-vastare @Sai-ganesh-0004 @sanchitc05 @T-
Rahul-prabhu-38 @shreyad2806 @Muskan-bhatt249 @devxMani @neeru24 @sejals23 @Yash-Vashishth @shauryaq05 if anybody of you want to create a ui from scratch, preferably in react , comment fast!

**Comment by smog-root** [comment]
@tanishaness Add the labels to my PR! You are not relying on the PR!!
#34 add all labels added to the issue!! 💢

**Comment by smog-root** [comment]
#34 it is not reflected to leaderboard!

**Comment by sanchitc05** [comment]
I don't know react that much, I just have a good proficiency in HTML, CSS, and JS. I could design a simple yet sophisticated structure for your website and to enhance it further other contributors are free to raise issues to it. Let me know what you think @tanishaness

**Comment by Varsha567** [comment]
HIii @tanishaness please add labels to my PR #15 messaged you multiple times but no response can u please update if possible?

**Comment by Yash-Vashishth** [comment]
Hi @tanishaness please add the level 2 tag, gssoc-ext and hacktoberfest tags to pr #21

I would also like to take up the ui issue that is assigned the level 3 tag from you

**Comment by neeru24** [comment]
Hi, @tanishaness Kindly add the labels to my PR https://github.com/tanishaness/SPROCTOR/pull/41

**Comment by sv410** [comment]
i can do it like this..
![light](https://github.com/user-attachments/assets/1b262674-14da-409a-86e9-8f76b9fdfca0)
![night](https://github.com/user-attachments/assets/622a9abb-e993-45db-846a-20dff3e4d58d)
using html css js

**Comment by Ananya-vastare** [comment]
@tanishaness I know only html, css not react will it be okay if I can still work on this issue
