### ISSUE TITLE
Add github workflow to automatically assign labels on new issue creation 

### ISSUE THREAD

**Issue by maniacedoc** [tanishaness/SPROCTOR#39]
This workflow would automatically assign hacktoberfest accepted and gssoc extd labels once the issue is created. This will save time of the project admin.

**Comment by vishnumur777** [comment]
It must be authenticative to @tanishaness whether issues are legit

**Comment by tanishaness** [comment]
> It must be authenticative to @tanishaness whether issues are legit for gssoc-ext and hacktoberfest.

exactly
