### ISSUE TITLE
Enable windows close button 

### ISSUE THREAD

**Issue by theomkardeshpande** [tanishaness/SPROCTOR#6]
Enable both windows close buttons to close the frame and windows, it is difficult for user to close the program

**Comment by AryaEjoumalai** [comment]
Hi, I can work in this issue, requesting addition of level 2 gssoc-ext label

**Comment by theomkardeshpande** [comment]
@AryaEjoumalai are u going to contribute to this issue ? 
If yes ping me on discord to discuss more.
 @omi140502
