### ISSUE TITLE
Enhancement of login page

### ISSUE THREAD

**Issue by Ananya-vastare** [tanishaness/SPROCTOR#66]
To create a robust login system for SPROCTOR, you can use Flask, a Python web framework, to build a scalable, browser-accessible login page that securely handles user authentication. User credentials can be stored in a password-protected Excel file (.xlsx), accessed with the openpyxl library, while pandas manages data retrieval. The HTML front end for the login page, created with Flask’s templating, allows users to input credentials, providing feedback on login status through Flask’s messaging. Flask serves as the backend that loads and verifies the credentials upon form submission. After configuring and running the Flask app, this login page will be available on localhost, allowing easy user access and secure authentication. This setup avoids Tkinter, ensuring flexibility for future expansions and browser-based accessibility.

@tanishaness please assign this issue to me thank you

**Comment by tanishaness** [comment]
Amazing
