### ISSUE TITLE
Add contributor.md file

### ISSUE THREAD

**Issue by Amulya-B28** [tanishaness/SPROCTOR#8]
I would like to add this because this file is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign me this task.

**Comment by Varsha567** [comment]
Hii @tanishaness could you please assign this to me?

**Comment by Varsha567** [comment]
hii @tanishaness I noticed that my contributions are not reflected on the leaderboard, and I would like to kindly request your assistance in rectifying this issue. It’s important for me to have my contributions acknowledged, and I believe they have met the required criteria.
Thank you for your attention to this matter. I appreciate your support, and I look forward to your response.
