### ISSUE TITLE
 Peer Comparison Tool.

### ISSUE THREAD

**Issue by smog-root** [tanishaness/SPROCTOR#9]
Implement a tool that compares student behaviors against their peers to identify outliers.

- Key Features: Provide insights into how individual behaviors compare to group averages.

i'm expecting a gssoc-ext and a level3 label.

@tanishaness Assign me!

**Comment by smog-root** [comment]
Can you also add a hacktoberfest-accepted lebal.!!

**Comment by tanishaness** [comment]
hey smog, I cant understand if im supposed to add the hacktober fest label
on all the gssoc issues? can you confirm

**Comment by smog-root** [comment]
Yes. You can add!! It's official said on the GSSoC discord!

**Comment by smog-root** [comment]
hey. i'm done doing this!
and i have added some features to it too!

i have sent you a friend request on discord. i will explain it to you and send a pull request??

what do you say??
